version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/resilience-stg01
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
